import type { TBDProducts } from "@shared/models/types";

export const BD_PRODUCTS: TBDProducts[] = [
  {
    id: "1",
    title: "Apple BYZ S852I",
    href: "/icons/products/AppleBYZS852I.png",
    current_price: "2927",
    old_price: "3527",
    rate: "4.7",
    type: "headphones",
  },
  {
    id: "2",
    title: "Apple EarPods",
    href: "/icons/products/AppleEarPods.png",
    current_price: "2327",
    old_price: "",
    rate: "4.5",
    type: "headphones",
  },
  {
    id: "3",
    title: "Apple EarPods",
    href: "/icons/products/AppleEarPods2.png",
    current_price: "2327",
    old_price: "",
    rate: "4.5",
    type: "headphones",
  },
  {
    id: "4",
    title: "Apple BYZ S852I",
    href: "/icons/products/AppleBYZS852I.png",
    current_price: "2927",
    old_price: "",
    rate: "4.7",
    type: "headphones",
  },
  {
    id: "5",
    title: "Apple EarPods",
    href: "/icons/products/AppleEarPods.png",
    current_price: "2327",
    old_price: "",
    rate: "4.5",
    type: "headphones",
  },
  {
    id: "6",
    title: "Apple EarPods",
    href: "/icons/products/AppleEarPods2.png",
    current_price: "2327",
    old_price: "",
    rate: "4.5",
    type: "headphones",
  },
  {
    id: "7",
    title: "Apple AirPods",
    href: "/icons/products/AppleAirPods.png",
    current_price: "9527",
    old_price: "",
    rate: "4.7",
    type: "wireless_headphones",
  },
  {
    id: "8",
    title: "GERLAX GH-04",
    href: "/icons/products/GERLAXGH04.png",
    current_price: "6527",
    old_price: "",
    rate: "4.7",
    type: "wireless_headphones",
  },
  {
    id: "9",
    title: "BOROFONE BO4",
    href: "/icons/products/BOROFONEBO4.png",
    current_price: "7527",
    old_price: "",
    rate: "4.7",
    type: "wireless_headphones",
  },
];
